<?php
$tinh_thanhpho = array(
  "0" => array("city_id"=>"HANOI","name"=>"TP. Hà Nội","mabnv"=>"01","matms"=>"101","matinh"=>"01"),
  "1" => array("city_id"=>"HOCHIMINH","name"=>"TP. Hồ Chí Minh","mabnv"=>"29","matms"=>"701","matinh"=>"79"),
  "2" => array("city_id"=>"CANTHO","name"=>"TP. Cần Thơ","mabnv"=>"33","matms"=>"815","matinh"=>"92"),
  "3" => array("city_id"=>"DANANG","name"=>"TP. Đà Nẵng","mabnv"=>"21","matms"=>"501","matinh"=>"48"),
  "4" => array("city_id"=>"HAIPHONG","name"=>"TP. Hải Phòng","mabnv"=>"04","matms"=>"103","matinh"=>"31"),
  "5" => array("city_id"=>"HUE","name"=>"TP. Huế","mabnv"=>"20","matms"=>"411","matinh"=>"46"),
  "6" => array("city_id"=>"ANGIANG","name"=>"An Giang","mabnv"=>"32","matms"=>"805","matinh"=>"91"),
  "7" => array("city_id"=>"BACNINH","name"=>"Bắc Ninh","mabnv"=>"02","matms"=>"223","matinh"=>"24"),
  "8" => array("city_id"=>"CAOBANG","name"=>"Cao Bằng","mabnv"=>"07","matms"=>"203","matinh"=>"04"),
  "9" => array("city_id"=>"CAMAU","name"=>"Cà Mau","mabnv"=>"34","matms"=>"823","matinh"=>"96"),
  "10" => array("city_id"=>"DAKLAK","name"=>"Đắk Lắk","mabnv"=>"25","matms"=>"605","matinh"=>"66"),
  "11" => array("city_id"=>"DIENBIEN","name"=>"Điện Biên","mabnv"=>"13","matms"=>"301","matinh"=>"11"),
  "12" => array("city_id"=>"DONGNAI","name"=>"Đồng Nai","mabnv"=>"28","matms"=>"713","matinh"=>"75"),
  "13" => array("city_id"=>"DONGTHAP","name"=>"Đồng Tháp","mabnv"=>"31","matms"=>"803","matinh"=>"82"),
  "14" => array("city_id"=>"GIALAI","name"=>"Gia Lai","mabnv"=>"24","matms"=>"603","matinh"=>"52"),
  "15" => array("city_id"=>"HATINH","name"=>"Hà Tĩnh","mabnv"=>"18","matms"=>"405","matinh"=>"42"),
  "16" => array("city_id"=>"HUNGYEN","name"=>"Hưng Yên","mabnv"=>"05","matms"=>"109","matinh"=>"33"),
  "17" => array("city_id"=>"KHANHHOA","name"=>"Khánh Hòa","mabnv"=>"23","matms"=>"511","matinh"=>"56"),
  "18" => array("city_id"=>"LAICHAU","name"=>"Lai Châu","mabnv"=>"14","matms"=>"302","matinh"=>"12"),
  "19" => array("city_id"=>"LAMDONG","name"=>"Lâm Đồng","mabnv"=>"26","matms"=>"703","matinh"=>"68"),
  "20" => array("city_id"=>"LANGSON","name"=>"Lạng Sơn","mabnv"=>"11","matms"=>"209","matinh"=>"20"),
  "21" => array("city_id"=>"LAOCAI","name"=>"Lào Cai","mabnv"=>"09","matms"=>"205","matinh"=>"15"),
  "22" => array("city_id"=>"NGHEAN","name"=>"Nghệ An","mabnv"=>"17","matms"=>"403","matinh"=>"40"),
  "23" => array("city_id"=>"NINHBINH","name"=>"Ninh Bình","mabnv"=>"06","matms"=>"117","matinh"=>"37"),
  "24" => array("city_id"=>"PHUTHO","name"=>"Phú Thọ","mabnv"=>"12","matms"=>"217","matinh"=>"25"),
  "25" => array("city_id"=>"QUANGNGAI","name"=>"Quảng Ngãi","mabnv"=>"22","matms"=>"505","matinh"=>"51"),
  "26" => array("city_id"=>"QUANGNINH","name"=>"Quảng Ninh","mabnv"=>"03","matms"=>"225","matinh"=>"22"),
  "27" => array("city_id"=>"QUANGTRI","name"=>"Quảng Trị","mabnv"=>"19","matms"=>"409","matinh"=>"44"),
  "28" => array("city_id"=>"SONLA","name"=>"Sơn La","mabnv"=>"15","matms"=>"303","matinh"=>"14"),
  "29" => array("city_id"=>"TAYNINH","name"=>"Tây Ninh","mabnv"=>"27","matms"=>"709","matinh"=>"80"),
  "30" => array("city_id"=>"THAINGUYEN","name"=>"Thái Nguyên","mabnv"=>"10","matms"=>"215","matinh"=>"19"),
  "31" => array("city_id"=>"THANHHOA","name"=>"Thanh Hóa","mabnv"=>"16","matms"=>"401","matinh"=>"38"),
  "32" => array("city_id"=>"TUYENQUANG","name"=>"Tuyên Quang","mabnv"=>"08","matms"=>"211","matinh"=>"08"),
  "33" => array("city_id"=>"VINHLONG","name"=>"Vĩnh Long","mabnv"=>"30","matms"=>"809","matinh"=>"86"),
);